// Root global Env will be generated by wrangler types.
// We declare/alias Env here for Worker backend typing.
export type WorkerEnv = Env;

export interface AuthContext {
	email: string | null;
	subject: string;
	mode: "access" | "local";
}

export interface ConnectAuthContext {
	connectId: string;
	name: string;
	prefix: string;
}

export class ApiError extends Error {
	constructor(
		public status: number,
		public code: string,
		message: string,
	) {
		super(message);
		this.name = "ApiError";
	}
}
